export const GET_COURSE_REQUEST = "GET_COURSE_REQUEST";
export const GET_COURSE_SUCCESS = "GET_COURSE_SUCCESS";
export const GET_COURSE_FAILURE = "GET_COURSE_FAILURE";

export const SET_SNACKBAR = "SHOW_SNACKBAR";

export const SUBSCRIBE_COURSE__REQUEST = "SUBSCRIBE_COURSE__REQUEST";
export const SUBSCRIBE_COURSE__SUCCESS = "SUBSCRIBE_COURSE__SUCCESS";
export const SUBSCRIBE_COURSE__FAILURE = "SUBSCRIBE_COURSE__FAILURE";

export const ADD_COURSE_REQUEST = "ADD_COURSE_REQUEST";
export const ADD_COURSE_SUCCESS = "ADD_COURSE_SUCCESS";
export const ADD_COURSE_FAILURE = "ADD_COURSE_FAILURE";

export const DELETE_COURSE_REQUEST = "DELETE_COURSE_REQUEST";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
export const DELETE_COURSE_FAILURE = "DELETE_COURSE_FAILURE";
