export const GET_COURSE_REQUEST = "GET_COURSE_REQUEST";
export const GET_COURSE_SUCCESS = "GET_COURSE_SUCCESS";
export const GET_COURSE_FAILURE = "GET_COURSE_FAILURE";

export const SET_SNACKBAR = "SHOW_SNACKBAR";
export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";

export const OPEN_DRAWER = "OPEN_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";

export const SUBSCRIBE_COURSE__REQUEST = "SUBSCRIBE_COURSE__REQUEST";
export const SUBSCRIBE_COURSE__SUCCESS = "SUBSCRIBE_COURSE__SUCCESS";
export const SUBSCRIBE_COURSE__FAILURE = "SUBSCRIBE_COURSE__FAILURE";

export const ADD_COURSE_REQUEST = "ADD_COURSE_REQUEST";
export const ADD_COURSE_SUCCESS = "ADD_COURSE_SUCCESS";
export const ADD_COURSE_FAILURE = "ADD_COURSE_FAILURE";

export const DELETE_COURSE_REQUEST = "DELETE_COURSE_REQUEST";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
export const DELETE_COURSE_FAILURE = "DELETE_COURSE_FAILURE";

export const ADD_CHAPTER_REQUEST = "DELETE_COURSE_REQUEST";
export const ADD_CHAPTER_SUCCESS = "DELETE_COURSE_SUCCESS";
export const ADD_CHAPTER_FAILURE = "DELETE_COURSE_FAILURE";

export const GET_CHAPTER_REQUEST = "DELETE_COURSE_REQUEST";
export const GET_CHAPTER_SUCCESS = "DELETE_COURSE_SUCCESS";
export const GET_CHAPTER_FAILURE = "DELETE_COURSE_FAILURE";

export const ADD_UPLOAD_REQUEST = "DELETE_UPLOAD_REQUEST";
export const ADD_UPLOAD_SUCCESS = "DELETE_UPLOAD_SUCCESS";
export const ADD_UPLOAD_FAILURE = "DELETE_UPLOAD_FAILURE";

export const GET_VIDEO_REQUEST = "DELETE_VIDEO_REQUEST";
export const GET_VIDEO_SUCCESS = "DELETE_VIDEO_SUCCESS";
export const GET_VIDEO_FAILURE = "DELETE_VIDEO_FAILURE";

export const ADD_QUIZ_REQUEST = "ADD_QUIZ_REQUEST";
export const ADD_QUIZ_SUCCESS = "ADD_QUIZ_SUCCESS";
export const ADD_QUIZ_FAILURE = "ADD_QUIZ_FAILURE";

export const GET_QUIZ_REQUEST = "GET_QUIZ_REQUEST";
export const GET_QUIZ_SUCCESS = "GET_QUIZ_SUCCESS";
export const GET_QUIZ_FAILURE = "GET_QUIZ_FAILURE";


